## PyTorch Tutorial - example1
MILA, November 2017 created by Sandeep Subramanian, <br>
modified by Sam,Liu


Getting Started
---------------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [1]:
from __future__ import print_function
import numpy as np
import torch

### Initialize a random tensor

In [2]:
torch.Tensor(5, 3)

tensor([[5.6769e+03, 3.0948e-41, 5.7453e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4076e+07, 2.0706e-19],
        [7.3909e+22, 2.4176e-12, 1.1625e+33],
        [8.9605e-01, 1.1632e+33, 5.6003e-02]])

### From a uniform distribution

In [3]:
torch.Tensor(5, 3).uniform_(-1, 1)

tensor([[ 0.0712,  0.7814, -0.7625],
        [ 0.0949,  0.3324,  0.5096],
        [-0.3215, -0.8707,  0.0575],
        [-0.5614, -0.3230,  0.3477],
        [ 0.3403, -0.0070, -0.7052]])

### Get it's shape

In [4]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

torch.Size([5, 3])


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |CPU Tensor| 
|----------|------|
|32-bit floating point		|torch.FloatTensor	|
|64-bit floating point		|torch.DoubleTensor	|
|16-bit floating point		|torch.HalfTensor	|
|8-bit integer (unsigned)	|torch.ByteTensor	| 
|8-bit integer (signed)		|torch.CharTensor	|
|16-bit integer (signed)	|torch.ShortTensor	|
|32-bit integer (signed)	|torch.IntTensor	|
|64-bit integer (signed)	|torch.LongTensor	|

### Creation from lists & numpy

In [5]:
z_list = [[1, 3], [2, 9]]
z_tensor = torch.LongTensor(z_list)

print(z_tensor.type())

torch.LongTensor


In [6]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


### Simple mathematical operations

In [7]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
y = x * torch.randn(5, 3)
print(y)

tensor([[ 0.7605, -0.2435, -0.3830],
        [ 0.6698,  0.1130, -0.2465],
        [ 0.9572, -1.3255,  0.0036],
        [ 0.8017, -0.0366,  0.3109],
        [-0.0631,  0.8614, -0.3993]])


In [8]:
y = x / torch.sqrt(torch.randn(5, 3) ** 2)
print(y)

tensor([[14.1449,  0.7642,  1.8585],
        [ 1.2187, -0.9488, -1.4919],
        [ 1.6364, -0.5949, -0.0046],
        [-0.3041, -0.0480,  0.7258],
        [-0.8817,  2.4246, -2.3724]])


### Broadcasting

In [9]:
print (x.size())
y = x + torch.randn(5, 1)
print(y)

torch.Size([5, 3])
tensor([[-0.7309, -1.4779, -0.9464],
        [ 2.3813,  0.8688,  1.0954],
        [ 2.2766,  1.0436,  1.6930],
        [ 0.1567,  0.6982,  1.6095],
        [-0.8439,  0.5500, -0.7834]])


### Reshape

In [10]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD)(Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)(AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


### Repeat

In [11]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


### GPU support

In [12]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.9537, 1.2066, 1.7382],
        [1.9578, 0.4452, 0.6718],
        [1.5760, 0.3430, 0.9924],
        [0.4027, 0.9442, 1.8555],
        [0.2741, 1.6680, 0.3346]], device='cuda:0')
tensor([[1.9537, 1.2066, 1.7382],
        [1.9578, 0.4452, 0.6718],
        [1.5760, 0.3430, 0.9924],
        [0.4027, 0.9442, 1.8555],
        [0.2741, 1.6680, 0.3346]], dtype=torch.float64)


### Move tensors on the CPU -> GPU

In [13]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
if torch.cuda.is_available():
    x = x.cuda(device=0)
    print(x)

tensor([[-0.7782,  0.3327, -0.3481],
        [-0.0272, -0.8448, -0.7944],
        [-0.6959,  0.5204,  0.2608],
        [-0.2203,  0.0886,  0.7475],
        [ 0.3075, -0.3202,  0.4930]])
tensor([[-0.7782,  0.3327, -0.3481],
        [-0.0272, -0.8448, -0.7944],
        [-0.6959,  0.5204,  0.2608],
        [-0.2203,  0.0886,  0.7475],
        [ 0.3075, -0.3202,  0.4930]], device='cuda:0')


## Numpy and torch.Tensor comparison
### Type

<table align='left'>
<thead>
<tr><th>Numpy                  </th><th>PyTorch                                 </th></tr>
</thead>
<tbody>
<tr><td><code>np.ndarray</code></td><td><code>torch.Tensor</code>               </td></tr>
<tr><td><code>np.float32</code></td><td><code>torch.float32; torch.float</code> </td></tr>
<tr><td><code>np.float64</code></td><td><code>torch.float64; torch.double</code></td></tr>
<tr><td><code>np.float16</code></td><td><code>torch.float16; torch.half</code>  </td></tr>
<tr><td><code>np.int8</code>   </td><td><code>torch.int8</code>                 </td></tr>
<tr><td><code>np.uint8</code>  </td><td><code>torch.uint8</code>                </td></tr>
<tr><td><code>np.int16</code>  </td><td><code>torch.int16; torch.short</code>   </td></tr>
<tr><td><code>np.int32</code>  </td><td><code>torch.int32; torch.int</code>     </td></tr>
<tr><td><code>np.int64</code>  </td><td><code>torch.int64; torch.long</code>    </td></tr>
</tbody>
</table>

### Numerical ranges

<table align='left'>
<thead>
<tr><th>Numpy                            </th><th>PyTorch                             </th></tr>
</thead>
<tbody>
<tr><td><code>np.arange(10)</code>       </td><td><code>torch.arange(10)</code>       </td></tr>
<tr><td><code>np.arange(2, 3, 0.1)</code></td><td><code>torch.arange(2, 3, 0.1)</code></td></tr>
<tr><td><code>np.linspace</code>         </td><td><code>torch.linspace</code>         </td></tr>
<tr><td><code>np.logspace</code>         </td><td><code>torch.logspace</code>         </td></tr>
</tbody>
</table>

### Attributes

<table align='left'>
<thead>
<tr><th>Numpy                 </th><th>PyTorch                  </th></tr>
</thead>
<tbody>
<tr><td><code>x.shape</code>  </td><td><code>x.shape</code>     </td></tr>
<tr><td><code>x.strides</code></td><td><code>x.stride()</code>  </td></tr>
<tr><td><code>x.ndim</code>   </td><td><code>x.dim()</code>     </td></tr>
<tr><td><code>x.data</code>   </td><td><code>x.data</code>      </td></tr>
<tr><td><code>x.size</code>   </td><td><code>x.nelement()</code></td></tr>
<tr><td><code>x.dtype</code>  </td><td><code>x.dtype</code>     </td></tr>
</tbody>
</table>

### Calculation
<table align='left'>
<thead>
<tr><th>Numpy                   </th><th>PyTorch                                    </th></tr>
</thead>
<tbody>
<tr><td><code>x.min</code>      </td><td><code>x.min</code>                         </td></tr>
<tr><td><code>x.argmin</code>   </td><td><code>x.argmin</code>                      </td></tr>
<tr><td><code>x.max</code>      </td><td><code>x.max</code>                         </td></tr>
<tr><td><code>x.argmax</code>   </td><td><code>x.argmax</code>                      </td></tr>
<tr><td><code>x.clip</code>     </td><td><code>x.clamp</code>                       </td></tr>
<tr><td><code>x.round</code>    </td><td><code>x.round</code>                       </td></tr>
<tr><td><code>np.floor(x)</code></td><td><code>torch.floor(x); x.floor()</code>     </td></tr>
<tr><td><code>np.ceil(x)</code> </td><td><code>torch.ceil(x); x.ceil()</code>       </td></tr>
<tr><td><code>x.trace</code>    </td><td><code>x.trace</code>                       </td></tr>
<tr><td><code>x.sum</code>      </td><td><code>x.sum</code>                         </td></tr>
<tr><td><code>x.cumsum</code>   </td><td><code>x.cumsum</code>                      </td></tr>
<tr><td><code>x.mean</code>     </td><td><code>x.mean</code>                        </td></tr>
<tr><td><code>x.std</code>      </td><td><code>x.std</code>                         </td></tr>
<tr><td><code>x.prod</code>     </td><td><code>x.prod</code>                        </td></tr>
<tr><td><code>x.cumprod</code>  </td><td><code>x.cumprod</code>                     </td></tr>
<tr><td><code>x.all</code>      </td><td><code>(x == 1).sum() == x.nelement()</code></td></tr>
<tr><td><code>x.any</code>      </td><td><code>(x == 1).sum() > 0</code>            </td></tr>
</tbody>
</table>